### ISSUE TITLE
Helpful + Toolbox Delays

### ISSUE THREAD

**Issue by soisyourface** [iaacornus/silverblue-postinstall_upgrade#1]
Thanks for creating this. Has some super helpful notes, even if I'm on kinoite and not silverblue.

One thing I was annoyed by was that frequently inside toolbox there would be these seconds-long pauses for the entire system. Easy fix/hack is to add `toolbox` to the `/etc/hosts` file outside of the toolbox.

This tip found in this [issue](https://github.com/containers/toolbox/issues/1059#issuecomment-1135307025).

Maybe some other reader coming here in the future will find this information useful.

**Comment by iaacornus** [comment]
thank you for that suggestion, ill be sure to incorporate it, cheers
